name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build-linux:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-11.0]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
        working-directory: v2/

      - name: Integration Tests
        run:  |
              chmod +x run.sh
              bash run.sh
        working-directory: integration_tests/

      - name: Build
        run: go build .
        working-directory: v2/cmd/nuclei/
